# This file is a template, and might need editing before it works on your project.
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Bash.gitlab-ci.yml

# See https://docs.gitlab.com/ee/ci/yaml/index.html for all available options

# you can delete this line if you're not using Docker

linux:ubuntu:jammy:
    stage: build
    tags: [docker, vulkan]
    image: ubuntu:jammy
    variables:
        GIT_SUBMODULE_STRATEGY: recursive
        GIT_SUBMODULE_DEPTH: 1
        pkg_format: deb
    before_script:
        -   DEBIAN_FRONTEND=noninteractive apt update -yqq
        -   DEBIAN_FRONTEND=noninteractive wget -qO- https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo tee /etc/apt/trusted.gpg.d/lunarg.asc
        -   DEBIAN_FRONTEND=noninteractive wget -qO /etc/apt/sources.list.d/lunarg-vulkan-jammy.list https://packages.lunarg.com/vulkan/lunarg-vulkan-jammy.list
        -   DEBIAN_FRONTEND=noninteractive apt update -yqq
        -   DEBIAN_FRONTEND=noninteractive apt install vulkan-sdk
        -   DEBIAN_FRONTEND=noninteractive mkdir -v logs/
    script:
        -   make | tee logs/make.log.txt
    rules:
        -   if: $CI_COMMIT_TAG
            when: on_success

before_script:
  - echo "Before script section"
  - echo "For example you might run an update here or install a build dependency"
  - echo "Or perhaps you might print out some debugging details"

after_script:
  - echo "After script section"
  - echo "For example you might do some cleanup here"

build1:
  stage: build
  script:
    - echo "Do your build here"

test1:
  stage: test
  script:
    - echo "Do a test here"
    - echo "For example run a test suite"

test2:
  stage: test
  script:
    - echo "Do another parallel test here"
    - echo "For example run a lint test"

deploy1:
  stage: deploy
  script:
    - echo "Do your deploy here"
  environment: production
